export {DesignHome} from "./ui/designHome/designHome";
export {DesignAbout} from "./ui/designAbout/designAbout";
export {DesignMaterial} from "./ui/designMaterial/designMaterial";
export {DesignEmail} from "./ui/designEmail/designEmail";
export {DesignPacking} from "./ui/designPacking/designPacking";
export {DesignInterface} from "./ui/designInterface/designInterface";
export {DesignCompany} from "./ui/designCompany/designCompany";
export {DesignVisualization} from "./ui/designVisualization/designVisualization";
export {DesignFooter} from "./ui/designFooter/designFooter";